---
- name: Upgrade Ubuntu/Debian
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    autoclean: yes
  become: yes
  when: "ansible_facts['os_family'] == 'Debian'"

- name: Upgrade CentOS
  yum:
    update_cache: yes
    state: latest
    name: '*'
  become: yes
  when: "ansible_facts['os_family'] == 'RedHat'"

- name: Reboot
  reboot:
  become: yes

