---
- name: Create instance
  hosts: localhost
  vars:
    servers:
      - name: matlab-image-ubuntu
        image: "8a8b5193-3704-4778-8efd-9d36ad0e29c3"
        flavor: 2cpu-8ram-hpcv3
        key_name: rbrisk_s3it
        nics:
          - net-name: uzh-only
        meta:
          group: matlab_image
          ssh_user: ubuntu
  roles:
    - { role: create_instances }

- name: Install Matlab
  hosts: matlab_image
  vars:
    matlab_version: R2020a
    iso_name: "{{ matlab_version }}_Linux.iso"
    iso_base_url: ''
    matlab_FIK: ''
    matlab_license_server: ''
  roles:
    - { role: upgrade_packages } 
    - { role: matlab_image }

