---
- name: Create instance
  hosts: localhost
  vars:
    servers:
      - name: matlab-image-ubuntu
        image: "a5d74672-bb5e-4cae-8969-559bc11c11f4"
        flavor: 2cpu-8ram-hpc
        key_name: ''
        nics:
          - net-name: uzh-only
        meta:
          group: matlab_image
          ssh_user: ubuntu
  roles:
    - { role: create_instances }

- name: Install Matlab
  hosts: matlab_image
  vars:
    matlab_version: R2019b
    iso_name: "{{ matlab_version }}_Linux.iso"
    iso_base_url: ''
    matlab_FIK: ''
    matlab_license_server: ''
  roles:
    - { role: upgrade_packages } 
    - { role: matlab_image }

