# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

set -o vi
set -o pipefail
PS1="\[\e[1;36m\]\u\[\e[1;33m\]@\h\[\e[0m\] \W\[\e[1;36m\]$\[\e[0m\] "
EDITOR=vim
VISUAL=vim
HISTCONTROL=ignoredups
export PS1 EDITOR VISUAL HISTCONTROL

[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases

eval $(keychain --eval --quiet)

