---
- name: Instantiation
  os_server:
    name: "{{ item.name }}"
    state: present
    key_name: "{{ item.key_name }}"
    image: "{{ item.image }}"
    flavor: "{{ item.flavor }}"
    nics: "{{ item.nics }}"
    wait: yes
  loop: "{{ servers }}"
  register: "os_hosts"

# os_server waits until the instance is created but not necessarily until it boots
- name: Timeout
  pause:
    minutes: 1
  when: os_hosts.changed 

- name: Add hosts to inventory
  add_host:
    name: "{{ item.openstack.name }}"
    groups: "{{ item.item.meta.group }}"
    ansible_host: "{{ item.openstack.accessIPv4 }}"
    ansible_ssh_user: "{{ item.item.meta.ssh_user }}"
  loop: "{{ os_hosts.results }}"

