---
- name: Instantiation
  os_server:
    name: "{{ item.name }}"
    state: present
    key_name: "{{ item.key_name }}"
    image: "{{ item.image }}"
    flavor: "{{ item.flavor }}"
    nics: "{{ item.nics }}"
  loop: "{{ servers }}"
  register: "os_hosts"

- name: Add hosts to inventory
  add_host:
    name: "{{ item.openstack.name }}"
    groups: "{{ item.item.meta.group }}"
    ansible_host: "{{ item.openstack.accessIPv4 }}"
  loop: "{{ os_hosts.results }}"

